CREATE TABLE `jobh_user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`onboardingCompleted` int DEFAULT 0,
	`onboardingStep` int DEFAULT 1,
	`targetJobTitle` varchar(256),
	`targetIndustry` varchar(128),
	`experienceLevel` varchar(64),
	`linkedinUrl` varchar(512),
	`linkedinHeadline` text,
	`linkedinAbout` text,
	`resumesCreated` int DEFAULT 0,
	`jobsTracked` int DEFAULT 0,
	`interviewsCompleted` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobh_user_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobh_user_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `linkedin_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('headline','about','post') NOT NULL,
	`inputKeywords` json,
	`inputTone` varchar(64),
	`inputLanguage` varchar(32) DEFAULT 'English',
	`inputProfile` varchar(64),
	`generatedContent` text NOT NULL,
	`isFavorite` int DEFAULT 0,
	`isUsed` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `linkedin_content_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `resumes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`type` enum('base','tailored') NOT NULL DEFAULT 'base',
	`isDefault` int DEFAULT 0,
	`score` int DEFAULT 0,
	`targetJobId` int,
	`targetJobTitle` varchar(256),
	`targetCompany` varchar(256),
	`personalInfo` json,
	`summary` text,
	`experience` json,
	`education` json,
	`skills` json,
	`projects` json,
	`certifications` json,
	`awards` json,
	`publications` json,
	`volunteering` json,
	`templateId` varchar(64) DEFAULT 'default',
	`colorScheme` varchar(64) DEFAULT 'professional',
	`fontSize` varchar(32) DEFAULT 'medium',
	`sectionVisibility` json,
	`pdfUrl` varchar(512),
	`pdfGeneratedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `resumes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tracked_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`company` varchar(256) NOT NULL,
	`position` varchar(256) NOT NULL,
	`location` varchar(256),
	`jobUrl` varchar(512),
	`salaryMin` decimal(12,2),
	`salaryMax` decimal(12,2),
	`salaryCurrency` varchar(8) DEFAULT 'USD',
	`status` enum('saved','applied','interviewing','offer','rejected','withdrawn') NOT NULL DEFAULT 'saved',
	`appliedAt` timestamp,
	`applicationMethod` varchar(64),
	`contactName` varchar(128),
	`contactEmail` varchar(256),
	`contactPhone` varchar(32),
	`notes` text,
	`tags` json,
	`interviewDate` timestamp,
	`interviewType` varchar(64),
	`resumeId` int,
	`source` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tracked_jobs_id` PRIMARY KEY(`id`)
);
